version: 2

sources:
  - name: raw ##name you give to this group of tables config
    schema: raw ## schema name in database
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: product_category_name_translation
      - name: sellers
